name: ${project.name}
version: ${project.version}
description: ${project.description}
author: maciekmm
website: ${project.url}
main: ${main.class}
softdepend: [ImmortalCustom]
commands:
  countable:
    description: Make item countable
    usage: /<command> - makes item countable
    permission: usecounter.countable